### ISSUE TITLE
 ImGUI assertion failure when selecting a non-folder item in the Library

### ISSUE THREAD

**Issue by Minmoose** [Etheirys/Brio#107]
Assertion failure log for future reference:

```
 ImGui assertion failed: "id != window->ID && \"Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works!\"" at "D:\a\Dalamud\Dalamud\lib\cimgui\imgui\imgui.cpp":9008
	   at Dalamud.Interface.Internal.Asserts.AssertHandler.OnImGuiAssert(String expr, String file, Int32 line)
	   at ImGuiNET.ImGuiNative.igButton(Byte* label, Vector2 size)
	   at ImGuiNET.ImGuiNative.igButton(Byte* label, Vector2 size)
	   at ImGuiNET.ImGui.Button(String label, Vector2 size)
	   at Brio.UI.Controls.Stateless.ImBrio.Button(String label, FontAwesomeIcon icon, Vector2 size, String hoverText)
	   at Brio.Files.PoseFileInfo.DrawActions(FileEntry fileEntry, Boolean isModal)
	   at Brio.Library.Sources.FileEntry.DrawActions(Boolean isModal)
	   at Brio.UI.Windows.LibraryWindow.DrawInternal()
	   at Brio.UI.Windows.LibraryWindow.Draw()
	   at Dalamud.Interface.Windowing.Window.DrawInternal(WindowDrawFlags internalDrawFlags, WindowSystemPersistence persistence)
	   at Dalamud.Interface.Windowing.WindowSystem.Draw()
	   at Brio.UI.UIManager.DrawUI()
	   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act)
	   at Dalamud.Utility.EventHandlerExtensions.InvokeSafely(Action act)
	   at Dalamud.Interface.UiBuilder.OnDraw()
	   at Dalamud.Interface.Internal.InterfaceManager.Display()
	   at ImGuiScene.RawDX11Scene.Render()
	   at Dalamud.Interface.Internal.InterfaceManager.DxgiSwapChainPresentDetour(IDXGISwapChain* swapChain, UInt32 syncInterval, UInt32 flags)
	   at Dalamud.Game.Framework.HandleFrameworkUpdate(Framework* thisPtr)
	

```

**Comment by Minmoose** [comment]
This assertion was fixed but I have found 2 more

![image](https://github.com/user-attachments/assets/28d77b74-74da-434b-94f3-d07f5f388305)
![image](https://github.com/user-attachments/assets/08a4ea98-a3ce-4574-82ad-404dd1234ff2)

**Comment by Minmoose** [comment]
```
01:05:53.552 | WRN | ImGui assertion failed: "id != window->ID && \"Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works!\"" at "D:\a\Dalamud\Dalamud\lib\cimgui\imgui\imgui.cpp":9008
	   at Dalamud.Interface.Internal.Asserts.AssertHandler.<>c.<OnImGuiAssert>b__19_0()
	   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
	   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
	   at System.Lazy`1.CreateValue()
	   at Dalamud.Interface.Internal.Asserts.AssertHandler.OnImGuiAssert(String expr, String file, Int32 line)
	   at ImGuiNET.ImGuiNative.igInputText(Byte* label, Byte* buf, UInt32 buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, Void* user_data)
	   at ImGuiNET.ImGuiNative.igInputText(Byte* label, Byte* buf, UInt32 buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, Void* user_data)
	   at ImGuiNET.ImGui.InputText(String label, String& input, UInt32 maxLength, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, IntPtr user_data)
	   at ImGuiNET.ImGui.InputText(String label, String& input, UInt32 maxLength, ImGuiInputTextFlags flags)
	   at Brio.UI.Controls.Editors.ActionTimelineEditor.DrawCutscene()
	   at Brio.UI.Controls.Editors.ActionTimelineEditor.Draw(Boolean drawAdvanced, ActionTimelineCapability capability)
	   at Brio.UI.Windows.Specialized.ActionTimelineWindow.Draw()
	   at Dalamud.Interface.Windowing.Window.DrawInternal(WindowDrawFlags internalDrawFlags, WindowSystemPersistence persistence)
	   at Dalamud.Interface.Windowing.WindowSystem.Draw()
	   at Brio.UI.UIManager.DrawUI()
	   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act)
	   at Dalamud.Utility.EventHandlerExtensions.InvokeSafely(Action act)
	   at Dalamud.Interface.UiBuilder.OnDraw()
	   at Dalamud.Interface.Internal.InterfaceManager.Display()
	   at ImGuiScene.RawDX11Scene.Render()
	   at Dalamud.Interface.Internal.InterfaceManager.DxgiSwapChainPresentDetour(IDXGISwapChain* swapChain, UInt32 syncInterval, UInt32 flags)
	   at Dalamud.Game.Framework.HandleFrameworkUpdate(Framework* thisPtr)
	

```

**Comment by Minmoose** [comment]
For the purposes of knowledge!!! ™️The ToggleButtonStrip button was causing these assertion errors, leading to some users to a crash as found in #174 (fixed in 0.5.2.1)


<img width="865" height="563" alt="Image" src="https://github.com/user-attachments/assets/112ccc21-43a2-4483-ae6a-743497b33ab4" />

<img width="836" height="523" alt="Image" src="https://github.com/user-attachments/assets/d04423a1-6bff-4ba1-848a-8fa9cef187a2" />

<img width="791" height="483" alt="Image" src="https://github.com/user-attachments/assets/e5ce39b1-5958-4e3f-8695-75ffbe31a642" />

<img width="776" height="463" alt="Image" src="https://github.com/user-attachments/assets/acc21eba-f9c5-4f00-ac85-b67406e77be5" />

<img width="776" height="443" alt="Image" src="https://github.com/user-attachments/assets/2a613b71-b5f9-4e71-b852-36db329849c4" />

<img width="865" height="563" alt="Image" src="https://github.com/user-attachments/assets/daa6f332-825d-483b-9912-3ee79ad0bde0" />
