### ISSUE TITLE
Can't run the /brio command to start.

### ISSUE THREAD

**Issue by jackeyloveqwess** [Etheirys/Brio#40]
Can't run the /brio command to start the Brio. Are there any plugin conflicts or something?

**Comment by Cerrelle** [comment]
Same thing... it looks like  Brio may be having issues with the net8 update for Dalamud

`2024-03-19 17:19:16.268 -05:00 [ERR] [Brio] Failed to start Brio in 145ms
System.Collections.Generic.KeyNotFoundException: Can't find a signature of 48 8B 0D B1 73 10 02 E9 44 7D 32
   at Dalamud.Game.SigScanner.Scan(IntPtr baseAddress, Int32 size, String signature) in C:\goatsoft\companysecrets\dalamud\Game\SigScanner.cs:line 125
   at Dalamud.Game.SigScanner.ScanText(String signature) in C:\goatsoft\companysecrets\dalamud\Game\SigScanner.cs:line 281
   at Brio.Game.Posing.SkeletonService..ctor(EntityManager entityManager, ObjectMonitorService monitorService, GPoseService gPoseService, IKService ikService, IFramework framework, ISigScanner scanner, IGameInteropProvider hooking) in D:\a\Brio\Brio\Brio\Game\Posing\SkeletonService.cs:line 62
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Brio.Brio.<>c__DisplayClass6_0.<.ctor>b__0() in D:\a\Brio\Brio\Brio\Brio.cs:line 57
`

**Comment by ClaraCatte** [comment]
Having the same issue when trying to gpose.

**Comment by Minmoose** [comment]
Fixed by #41
